spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: Ashish@98123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
